import notes from './notes';
import books from './books';
import tags from './tags';
import db from './db';
import session from './session';
import queryContext from './query-context';
import editingNote from './editing-note';
import config from './config';
import editor from './editor';
import navigation from './navigation';
import sidebar from './sidebar';
import stats from './stats';
import searchBar from './search-bar';
import assistiveError from './assistive-error';
import type { State } from '../types';
declare const _default: {
    notes: typeof notes;
    books: typeof books;
    tags: typeof tags;
    db: typeof db;
    config: typeof config;
    session: typeof session;
    queryContext: typeof queryContext;
    editingNote: typeof editingNote;
    editor: typeof editor;
    navigation: typeof navigation;
    sidebar: typeof sidebar;
    searchBar: typeof searchBar;
    stats: typeof stats;
    assistiveError: typeof assistiveError;
};
export default _default;
export declare const initialState: State;
